export const ctaCardsData = [
    {
        id: 1,
        title: "cardDataLoginTitle",
        description: "cardDataLoginDescription",
        buttonText: "cardDataLoginButtonText",
        imageSrc: "/pictures/cta-images/image-cta-login.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/login",
        imagePosition: "right",
    },
    {
        id: 2,
        title: "cardDataMenuTitle",
        description: "cardDataMenuDescription",
        buttonText: "cardDataMenuButtonText",
        imageSrc: "/pictures/cta-images/image-cta-menu.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/menu",
        imagePosition: "left",
    },
    {
        id: 3,
        title: "cardDataBookingTitle",
        description: "cardDataBookingDescription",
        buttonText: "cardDataBookingButtonText",
        imageSrc: "/pictures/cta-images/image-cta-bookings.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/bookings",
        imagePosition: "left",
    },
    {
        id: 4,
        title: "cardDataOrdersTitle",
        description: "cardDataOrdersDescription",
        buttonText: "cardDataOrdersButtonText",
        imageSrc: "/pictures/cta-images/image-cta-orders.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/orders",
        imagePosition: "right",
    },
];
