export const ctaCardsData = [
    {
        id: 1,
        title: "cta_cards.card_data_login_title",
        description: "cta_cards.card_data_login_description",
        buttonText: "cta_cards.card_data_login_button_text",
        imageSrc: "/pictures/cta-images/image-cta-login.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/login",
        imagePosition: "right",
    },
    {
        id: 2,
        title: "cta_cards.card_data_menu_title",
        description: "cta_cards.card_data_menu_description",
        buttonText: "cta_cards.card_data_menu_button_text",
        imageSrc: "/pictures/cta-images/image-cta-menu.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/menu",
        imagePosition: "left",
    },
    {
        id: 3,
        title: "cta_cards.card_data_booking_title",
        description: "cta_cards.card_data_booking_description",
        buttonText: "cta_cards.card_data_booking_button_text",
        imageSrc: "/pictures/cta-images/image-cta-bookings.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/bookings",
        imagePosition: "left",
    },
    {
        id: 4,
        title: "cta_cards.card_data_orders_title",
        description: "cta_cards.card_data_orders_description",
        buttonText: "cta_cards.card_data_orders_button_text",
        imageSrc: "/pictures/cta-images/image-cta-orders.webp",
        imageData: "",
        imageAlt: "",
        redirectTo: "/orders",
        imagePosition: "right",
    },
];
